//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikAcademy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHoursLog
    {
        public int WorkHoursLogId { get; set; }
        public int WorkHoursld { get; set; }
        public System.DateTime Date { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string Command { get; set; }
    
        public virtual WorkHour WorkHour { get; set; }
    }
}
